# https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck # Errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases.
    - gosimple # Linter for Go source code that specializes in simplifying code.
    - govet # Vet examines Go source code and reports suspicious constructs. It is roughly the same as 'go vet' and uses its passes.
    - ineffassign # Detects when assignments to existing variables are not used.
    - staticcheck # It's a set of rules from staticcheck. It's not the same thing as the staticcheck binary. The author of staticcheck doesn't support or approve the use of staticcheck as a library inside golangci-lint.
    - unused # Checks Go code for unused constants, variables, functions and types.
    - godot # Check if comments end in a period.
    - gofmt # Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification.
    - goimports # Check import statements are formatted according to the 'goimport' command. Reformat imports in autofix mode.
    - misspell # Finds commonly misspelled English words.
    - revive # Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint.
    - whitespace # Whitespace is a linter that checks for unnecessary newlines at the start and end of functions, if, for, etc.
    - prealloc # Finds slice declarations that could potentially be pre-allocated.

linters-settings:
  gosimple:
    # https://staticcheck.dev/docs/checks/
    checks: [ "all", "-S1000"]
  revive:
    severity: warning
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-naming
      - name: var-naming
        disabled: false
        arguments:
          - [ "IP","ID","API","HTTP","IDS" ]
          - [ ]
          - - skipPackageNameChecks: true
          - - upperCaseConst: true
