// Code generated by mockery v2.43.2. DO NOT EDIT.

package counter

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockHitMethod is an autogenerated mock type for the HitMethod type
type MockHitMethod struct {
	mock.Mock
}

type MockHitMethod_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHitMethod) EXPECT() *MockHitMethod_Expecter {
	return &MockHitMethod_Expecter{mock: &_m.Mock}
}

// GetHitOfDaily provides a mock function with given fields: ctx, id, t
func (_m *MockHitMethod) GetHitOfDaily(ctx context.Context, id string, t time.Time) (*Score, error) {
	ret := _m.Called(ctx, id, t)

	if len(ret) == 0 {
		panic("no return value specified for GetHitOfDaily")
	}

	var r0 *Score
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*Score, error)); ok {
		return rf(ctx, id, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *Score); ok {
		r0 = rf(ctx, id, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Score)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, id, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHitMethod_GetHitOfDaily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHitOfDaily'
type MockHitMethod_GetHitOfDaily_Call struct {
	*mock.Call
}

// GetHitOfDaily is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - t time.Time
func (_e *MockHitMethod_Expecter) GetHitOfDaily(ctx interface{}, id interface{}, t interface{}) *MockHitMethod_GetHitOfDaily_Call {
	return &MockHitMethod_GetHitOfDaily_Call{Call: _e.mock.On("GetHitOfDaily", ctx, id, t)}
}

func (_c *MockHitMethod_GetHitOfDaily_Call) Run(run func(ctx context.Context, id string, t time.Time)) *MockHitMethod_GetHitOfDaily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockHitMethod_GetHitOfDaily_Call) Return(_a0 *Score, _a1 error) *MockHitMethod_GetHitOfDaily_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHitMethod_GetHitOfDaily_Call) RunAndReturn(run func(context.Context, string, time.Time) (*Score, error)) *MockHitMethod_GetHitOfDaily_Call {
	_c.Call.Return(run)
	return _c
}

// GetHitOfDailyAndTotal provides a mock function with given fields: ctx, id, t
func (_m *MockHitMethod) GetHitOfDailyAndTotal(ctx context.Context, id string, t time.Time) (*Score, *Score, error) {
	ret := _m.Called(ctx, id, t)

	if len(ret) == 0 {
		panic("no return value specified for GetHitOfDailyAndTotal")
	}

	var r0 *Score
	var r1 *Score
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*Score, *Score, error)); ok {
		return rf(ctx, id, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *Score); ok {
		r0 = rf(ctx, id, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Score)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) *Score); ok {
		r1 = rf(ctx, id, t)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*Score)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, time.Time) error); ok {
		r2 = rf(ctx, id, t)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockHitMethod_GetHitOfDailyAndTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHitOfDailyAndTotal'
type MockHitMethod_GetHitOfDailyAndTotal_Call struct {
	*mock.Call
}

// GetHitOfDailyAndTotal is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - t time.Time
func (_e *MockHitMethod_Expecter) GetHitOfDailyAndTotal(ctx interface{}, id interface{}, t interface{}) *MockHitMethod_GetHitOfDailyAndTotal_Call {
	return &MockHitMethod_GetHitOfDailyAndTotal_Call{Call: _e.mock.On("GetHitOfDailyAndTotal", ctx, id, t)}
}

func (_c *MockHitMethod_GetHitOfDailyAndTotal_Call) Run(run func(ctx context.Context, id string, t time.Time)) *MockHitMethod_GetHitOfDailyAndTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockHitMethod_GetHitOfDailyAndTotal_Call) Return(daily *Score, total *Score, err error) *MockHitMethod_GetHitOfDailyAndTotal_Call {
	_c.Call.Return(daily, total, err)
	return _c
}

func (_c *MockHitMethod_GetHitOfDailyAndTotal_Call) RunAndReturn(run func(context.Context, string, time.Time) (*Score, *Score, error)) *MockHitMethod_GetHitOfDailyAndTotal_Call {
	_c.Call.Return(run)
	return _c
}

// GetHitOfDailyByRange provides a mock function with given fields: ctx, id, timeRange
func (_m *MockHitMethod) GetHitOfDailyByRange(ctx context.Context, id string, timeRange []time.Time) ([]*Score, error) {
	ret := _m.Called(ctx, id, timeRange)

	if len(ret) == 0 {
		panic("no return value specified for GetHitOfDailyByRange")
	}

	var r0 []*Score
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []time.Time) ([]*Score, error)); ok {
		return rf(ctx, id, timeRange)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []time.Time) []*Score); ok {
		r0 = rf(ctx, id, timeRange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Score)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []time.Time) error); ok {
		r1 = rf(ctx, id, timeRange)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHitMethod_GetHitOfDailyByRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHitOfDailyByRange'
type MockHitMethod_GetHitOfDailyByRange_Call struct {
	*mock.Call
}

// GetHitOfDailyByRange is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - timeRange []time.Time
func (_e *MockHitMethod_Expecter) GetHitOfDailyByRange(ctx interface{}, id interface{}, timeRange interface{}) *MockHitMethod_GetHitOfDailyByRange_Call {
	return &MockHitMethod_GetHitOfDailyByRange_Call{Call: _e.mock.On("GetHitOfDailyByRange", ctx, id, timeRange)}
}

func (_c *MockHitMethod_GetHitOfDailyByRange_Call) Run(run func(ctx context.Context, id string, timeRange []time.Time)) *MockHitMethod_GetHitOfDailyByRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]time.Time))
	})
	return _c
}

func (_c *MockHitMethod_GetHitOfDailyByRange_Call) Return(_a0 []*Score, _a1 error) *MockHitMethod_GetHitOfDailyByRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHitMethod_GetHitOfDailyByRange_Call) RunAndReturn(run func(context.Context, string, []time.Time) ([]*Score, error)) *MockHitMethod_GetHitOfDailyByRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetHitOfTotal provides a mock function with given fields: ctx, id
func (_m *MockHitMethod) GetHitOfTotal(ctx context.Context, id string) (*Score, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetHitOfTotal")
	}

	var r0 *Score
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Score, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Score); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Score)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHitMethod_GetHitOfTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHitOfTotal'
type MockHitMethod_GetHitOfTotal_Call struct {
	*mock.Call
}

// GetHitOfTotal is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockHitMethod_Expecter) GetHitOfTotal(ctx interface{}, id interface{}) *MockHitMethod_GetHitOfTotal_Call {
	return &MockHitMethod_GetHitOfTotal_Call{Call: _e.mock.On("GetHitOfTotal", ctx, id)}
}

func (_c *MockHitMethod_GetHitOfTotal_Call) Run(run func(ctx context.Context, id string)) *MockHitMethod_GetHitOfTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockHitMethod_GetHitOfTotal_Call) Return(_a0 *Score, _a1 error) *MockHitMethod_GetHitOfTotal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHitMethod_GetHitOfTotal_Call) RunAndReturn(run func(context.Context, string) (*Score, error)) *MockHitMethod_GetHitOfTotal_Call {
	_c.Call.Return(run)
	return _c
}

// IncreaseHitOfDaily provides a mock function with given fields: ctx, id, t, ttl
func (_m *MockHitMethod) IncreaseHitOfDaily(ctx context.Context, id string, t time.Time, ttl time.Duration) (*Score, error) {
	ret := _m.Called(ctx, id, t, ttl)

	if len(ret) == 0 {
		panic("no return value specified for IncreaseHitOfDaily")
	}

	var r0 *Score
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Duration) (*Score, error)); ok {
		return rf(ctx, id, t, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Duration) *Score); ok {
		r0 = rf(ctx, id, t, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Score)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Duration) error); ok {
		r1 = rf(ctx, id, t, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHitMethod_IncreaseHitOfDaily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncreaseHitOfDaily'
type MockHitMethod_IncreaseHitOfDaily_Call struct {
	*mock.Call
}

// IncreaseHitOfDaily is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - t time.Time
//   - ttl time.Duration
func (_e *MockHitMethod_Expecter) IncreaseHitOfDaily(ctx interface{}, id interface{}, t interface{}, ttl interface{}) *MockHitMethod_IncreaseHitOfDaily_Call {
	return &MockHitMethod_IncreaseHitOfDaily_Call{Call: _e.mock.On("IncreaseHitOfDaily", ctx, id, t, ttl)}
}

func (_c *MockHitMethod_IncreaseHitOfDaily_Call) Run(run func(ctx context.Context, id string, t time.Time, ttl time.Duration)) *MockHitMethod_IncreaseHitOfDaily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockHitMethod_IncreaseHitOfDaily_Call) Return(_a0 *Score, _a1 error) *MockHitMethod_IncreaseHitOfDaily_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHitMethod_IncreaseHitOfDaily_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Duration) (*Score, error)) *MockHitMethod_IncreaseHitOfDaily_Call {
	_c.Call.Return(run)
	return _c
}

// IncreaseHitOfTotal provides a mock function with given fields: ctx, id
func (_m *MockHitMethod) IncreaseHitOfTotal(ctx context.Context, id string) (*Score, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncreaseHitOfTotal")
	}

	var r0 *Score
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Score, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Score); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Score)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHitMethod_IncreaseHitOfTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncreaseHitOfTotal'
type MockHitMethod_IncreaseHitOfTotal_Call struct {
	*mock.Call
}

// IncreaseHitOfTotal is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockHitMethod_Expecter) IncreaseHitOfTotal(ctx interface{}, id interface{}) *MockHitMethod_IncreaseHitOfTotal_Call {
	return &MockHitMethod_IncreaseHitOfTotal_Call{Call: _e.mock.On("IncreaseHitOfTotal", ctx, id)}
}

func (_c *MockHitMethod_IncreaseHitOfTotal_Call) Run(run func(ctx context.Context, id string)) *MockHitMethod_IncreaseHitOfTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockHitMethod_IncreaseHitOfTotal_Call) Return(_a0 *Score, _a1 error) *MockHitMethod_IncreaseHitOfTotal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHitMethod_IncreaseHitOfTotal_Call) RunAndReturn(run func(context.Context, string) (*Score, error)) *MockHitMethod_IncreaseHitOfTotal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHitMethod creates a new instance of MockHitMethod. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHitMethod(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHitMethod {
	mock := &MockHitMethod{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
