// Code generated by mockery v2.43.2. DO NOT EDIT.

package limiter

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBlacklistMethod is an autogenerated mock type for the BlacklistMethod type
type MockBlacklistMethod struct {
	mock.Mock
}

type MockBlacklistMethod_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlacklistMethod) EXPECT() *MockBlacklistMethod_Expecter {
	return &MockBlacklistMethod_Expecter{mock: &_m.Mock}
}

// AddBlackList provides a mock function with given fields: ctx, id
func (_m *MockBlacklistMethod) AddBlackList(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AddBlackList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBlacklistMethod_AddBlackList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBlackList'
type MockBlacklistMethod_AddBlackList_Call struct {
	*mock.Call
}

// AddBlackList is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBlacklistMethod_Expecter) AddBlackList(ctx interface{}, id interface{}) *MockBlacklistMethod_AddBlackList_Call {
	return &MockBlacklistMethod_AddBlackList_Call{Call: _e.mock.On("AddBlackList", ctx, id)}
}

func (_c *MockBlacklistMethod_AddBlackList_Call) Run(run func(ctx context.Context, id string)) *MockBlacklistMethod_AddBlackList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBlacklistMethod_AddBlackList_Call) Return(_a0 error) *MockBlacklistMethod_AddBlackList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlacklistMethod_AddBlackList_Call) RunAndReturn(run func(context.Context, string) error) *MockBlacklistMethod_AddBlackList_Call {
	_c.Call.Return(run)
	return _c
}

// IsBlackList provides a mock function with given fields: ctx, id
func (_m *MockBlacklistMethod) IsBlackList(ctx context.Context, id string) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IsBlackList")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlacklistMethod_IsBlackList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBlackList'
type MockBlacklistMethod_IsBlackList_Call struct {
	*mock.Call
}

// IsBlackList is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBlacklistMethod_Expecter) IsBlackList(ctx interface{}, id interface{}) *MockBlacklistMethod_IsBlackList_Call {
	return &MockBlacklistMethod_IsBlackList_Call{Call: _e.mock.On("IsBlackList", ctx, id)}
}

func (_c *MockBlacklistMethod_IsBlackList_Call) Run(run func(ctx context.Context, id string)) *MockBlacklistMethod_IsBlackList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBlacklistMethod_IsBlackList_Call) Return(_a0 bool, _a1 error) *MockBlacklistMethod_IsBlackList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlacklistMethod_IsBlackList_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockBlacklistMethod_IsBlackList_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBlacklistMethod creates a new instance of MockBlacklistMethod. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlacklistMethod(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlacklistMethod {
	mock := &MockBlacklistMethod{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
